### ISSUE TITLE
Pass non-slot-level properties from partner config to parcels

### ISSUE THREAD

**Issue by katzhang-ias** [indexexchange/integral-ad-science-adapter#2]
Hi @ix-certification ,

Wondering if there's a way to pass properties unrelated to slots from the config to parcels. Example:
https://github.com/indexexchange/integral-ad-science-adapter/blob/development-v2/spec/support/mockPartnerConfig.json#L2

How can I access the `timeout` value from parcels? From the way parcels are generated (https://github.com/indexexchange/integral-ad-science-adapter/blob/development-v2/spec/generateRequestObj.spec.js#L28) `timeout` is skipped.

**Comment by dave-atx** [comment]
@johnnyindex in case you didn't see this

**Comment by katzhang-ias** [comment]
Hey guys @johnnyindex @ix-certification any updates?

**Comment by ix-certification** [comment]
Hi guys,

Sorry for the delays:
So parcels are based on slots being requested so configs unrelated to slots will not be provided. If you check the top of the module file (integral-ad-science-nob.js) the input is a configs object which is passed into the module constructor and custom page-level properties in the config should be accessible through that.

Can you please clarify why you need access the timeout property? If you are using the standard functions the request timeout should be handled by the library, unless you are looking to pass the timeout as part of the request.

Thanks

**Comment by katzhang-ias** [comment]
Hi @ix-certification ,

Thanks for the response! Sounds like I need to pass in the config object to generate a request? I actually don't need the timeout property; IAS needs the publisher to specify a client ID so actually I'm trying to access that.

**Comment by ix-certification** [comment]
Hi @katzhang-ias 

The entire config is being passed in here:
https://github.com/indexexchange/integral-ad-science-adapter/blob/development-v2/integral-ad-science-nob.js#L47

The `configs` var is accessible for you to use.

The best practice would be to assign the client id as a private variable and refer to it from generateRequestObj.

**Comment by katzhang-ias** [comment]
Thanks!
