### ISSUE TITLE
Get around with identical keys in request object

### ISSUE THREAD

**Issue by katzhang-ias** [indexexchange/integral-ad-science-adapter#3]
Hi @ix-certification ,

IAS endpoint supports single request for multiple slots but the endpoint only accepts requests with query string like this:

`?a=123&slot={id:slot-1,s:100.200,p:/sports/4/3}&slot={id:slot-2,s:300.250,p:/news/5/4}...`

In the case of `__generateRequestObj` the query string object will have to have multiple `slot` keys which wouldn't work. 

Any suggestions to get around with this? Thanks!

**Comment by dave-atx** [comment]
@johnnyindex in case you didn't see this

**Comment by ix-certification** [comment]
Hi @katzhang-ias 

As the query object will not work for your purpose. You can simply choose not to use it.

As a work around, you can simply append to the url string with the necessary query parameters needed.

**Comment by katzhang-ias** [comment]
Thanks!
